version: "3"
services:
  api:
    build: .
    ports:
      - 8080:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    #   - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    #   - ALGORITHM=HS256
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    